# Generated by Django 4.2.5 on 2023-10-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=120),
        ),
    ]
